name: CI CD Pipeline for Hospital Operations System

on:
  push:
    branches: [ develop, release, main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ACR_LOGIN_SERVER: ${{ vars.ACR_LOGIN_SERVER }}
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}

jobs:
  # Job 1: Build and Test source code with Maven
  build-test:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build & Test with Maven
        run: mvn clean package
      # Static code Analysis using SonarCloud
      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:4.0.0.4121:sonar \
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
          -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }} \
          -Dsonar.host.url=https://sonarcloud.io

      - name: SonarCloud Scan & Quality Gate
        uses: sonarsource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }}
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.java.binaries=target/classes
      # Upload the Software Artifact
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: hospital-jar
          path: target/*.jar
  # Job 2: Build and Push Docker Image
  docker-build:
    runs-on: ubuntu-latest
    needs: build-test
    environment: staging
    if: github.event_name =='push '
    steps:
      - uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: hospital-jar
          path: target

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR
        run: az acr login --name ${{ vars.ACR_LOGIN_SERVER }}
      # Build the Docker Image
      - name: Build Docker Image
        run: docker build -t ${{ vars.ACR_LOGIN_SERVER }}/${{ vars.IMAGE_NAME }}:${{ github.sha }}
      # Scan the built Docker Image against vulnerabilities
      - name: Scan Image for vulnerabilities using (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ vars.ACR_LOGIN_SERVER }}/${{ vars.IMAGE_NAME }}:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
      # Push the Image to ACR
      - name: Push Image to ACR
        run: docker push ${{ vars.ACR_LOGIN_SERVER }}/${{ vars.IMAGE_NAME }}:${{ github.sha }}


  # Job 3: Deploy to staging environment
  deploy-staging:
    runs-on: ubuntu-latest
    needs: docker-build
    if: github.ref == 'refs/heads/release'
    environment: staging
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

  # Job 4: Deploy to production environment with Manual Approval Gate
  deploy-prod:
    runs-on: ubuntu-latest
    needs: docker-build # Changed from deploy-staging to allow direct fixes to main if needed
    if: github.ref == 'refs/heads/main'
    environment: production # Triggers manual approval if configured in GitHub

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}